# -*- coding: utf-8 -*-
"""Copy of HW6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9F2w3HhBCCNp7yhAxu8l-Y5_6ABIBBZ
"""

import pandas as pd
import seaborn as sns

"""##Q3
Please follow the instructions below and inspect the outputs before you proceed. You can always check this original final to compare your results in your own copy.
"""

#You have to make sure that you were able to write the file to a csv while your were working in R
house=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATA-20260125T234113Z-1-001/DATA/house_prices.csv')
house.head()

from google.colab import drive
drive.mount('/content/drive')

"""a) For the states below, please select the rows from the house dataframe, and consider converting the date column to date data type as it may be coming in string format. Then use the head function to preview your new dataframe."""

states = ['Michigan', 'California', 'Texas', 'Indiana']

#your code goes here

import pandas as pd

#Define the states to filter
states = ['Michigan', 'California', 'Texas', 'Indiana']

#Convert date column to datetime format
house['date'] = pd.to_datetime(house['date'])

#Select rows from the house dataframe
house_subset = house[house['state'].isin(states)]

#Preview the new dataframe
print(house_subset.head())

"""b) Use the FacetGrid from seaborn to create line plots to represent house_price_index for each state. Please make the line color red, set ticks on x axis for years ['1980', '2000', '2020'], which you may have to convert date type again, put those years as labels, and set the titles for each small plot to their state names. In addition, set the y label to 'house price index' and remove the x label since it's obvious that these are years."""

#your code goes here
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Clean the date
house_subset['date'] = pd.to_datetime(house_subset['date'])

target_order = ['Michigan', 'California', 'Texas', 'Indiana']

#Create the FacetGrid
g = sns.FacetGrid(house_subset, col="state", col_wrap=4, height=3, col_order=target_order)

#Use map_dataframe
g.map_dataframe(sns.lineplot, x="date", y="house_price_index", color="red")

#Formatting
g.set_axis_labels("", "house price index")
g.set_titles("{col_name}")

#Apply 1980, 2000, 2020 ticks
tick_years = pd.to_datetime(['1980', '2000', '2020'])
for ax in g.axes.flat:
    ax.set_xticks(tick_years)
    ax.set_xticklabels(['1980', '2000', '2020'])

plt.tight_layout()
plt.show()

"""c) Draw a lineplot for 'house price perc', but color them based on the 'state' name which will have four lines in a single plot. Set a legend which will be at the bottom of your graph and have them horizantally positioned next to eachother. Again, set the y label to house_price_perc and remove the x label since it's obvious. (Note that my y label is still showing index. Please ignore that.)"""

#your code goes here

import matplotlib.pyplot as plt
import seaborn as sns

#Make plot size
plt.figure(figsize=(10,6))

#Draw the lineplot colored by state
sns.lineplot(data=house_subset, x='date', y='house_price_perc', hue='state')

#Format the labels
plt.ylabel('house_price_perc')
plt.xlabel('')

#Add a legend
plt.legend(loc='upper center',
                        bbox_to_anchor=(0.5, -0.1),
                        ncol=4,
                        fancybox=True,
                        shadow=True)
#Set the ticks for 1980, 2000, and 2020
tick_years = pd.to_datetime(['1980', '2000', '2020'])
plt.xticks(tick_years, ['1980', '2000', '2020'])

plt.tight_layout
plt.show()

"""##Q4
Please work on your 4th question below. Please feel free to add new code cells.
"""

#Your code goes here.
world_cup = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATA-20260125T234113Z-1-001/DATA/WorldCupMatches.csv')
world_cup.head()



#your code goes here. Just leaving an example output of an intermediate step for you to check the last two columns
#A hint to start with: team_pairs = world_cup.groupby(['Home Team Initials', 'Away Team Initials']).count().reset_index()
# (a) & (b) Group and caculate Count (weight) and Sum (HomeGoalTotal)

team_pairs = world_cup.groupby(['Home Team Initials', 'Away Team Initials']).agg(
    weight=('Home Team Goals', 'count'),
    HomeGoalTotal=('Home Team Goals', 'sum')
).reset_index()

# (c) previews the final dataframe
print(team_pairs.head())

# (d) Write to CSV
team_pairs.to_csv('team_pairs.csv', index=False)

"""Make sure that you only write four columns ('Home Team Initials', 'Away Team Initials', 'weight', 'HomeGoalTotal') from the data frame, team_pairs, to a csv file"""

